# Generated by Django 3.1.7 on 2021-03-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peak', '0002_auto_20210310_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
